# Site settings
title: Currant blog
email: miri@vhbv.net
description: > # this means to ignore newlines until "baseurl:"
  A boring blog with useless functionality and finite blog posts,
  it is the place you will want to leave within 3 minutes, and will
  leave within 1 minute. So, time is on, good luck ;-)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://zealous-hill-0a7463803.azurestaticapps.net/" # the base hostname & protocol for your site
twitter_username: mirivhbv
github_username:  mirivhbv

plugins:
  - jekyll-archives
  - jekyll-language-plugin

# Build settings
markdown: kramdown
permalink: /:year/:title/

jekyll-archives:
  enabled:
    - year
    - tags
    - categories
  layout: archive
  permalinks:
    year: '/:year/'
    tag: '/tag/:name/'
    category: '/category/:name/'
