# Site settings
title: Currant blog
email: miri@vhbv.net
description: > # this means to ignore newlines until "baseurl:"
  A boring blog with useless functionality and finitive blog posts,
  it is the place you will want to leave within 3 minutes, and will
  leave within 1 minute. So, time is on, good luck ;-)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ashy-pond-07bc2e700.azurestaticapps.net/" # the base hostname & protocol for your site
twitter_username: mirivhbv
github_username:  mirivhbv

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

collections:
  archives:
    output: true
    permalink: /archives/:path/
